"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Pencil, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatMoney } from "@/lib/money";
import { ExpenseDialog } from "./expense-dialog";

export type ExpenseView = { id: string; type: "EMPLOYEE" | "MATERIAL" | "FUEL" | "TRANSPORT" | "EQUIPMENT" | "SERVICE" | "OTHER"; title: string; amount: string; date: string; description: string | null; employeeName: string | null; vendorName: string | null; notes: string | null };
const labels: Record<ExpenseView["type"], string> = { EMPLOYEE: "Сотрудники", MATERIAL: "Материалы", FUEL: "Топливо", TRANSPORT: "Транспорт", EQUIPMENT: "Оборудование", SERVICE: "Услуги", OTHER: "Другое" };

export function ExpenseList({ projectId, expenses }: { projectId: string; expenses: ExpenseView[] }) {
  const router = useRouter(); const [type, setType] = useState<"ALL" | ExpenseView["type"]>("ALL"); const [sort, setSort] = useState("newest"); const [editing, setEditing] = useState<ExpenseView | null>(null); const [deleting, setDeleting] = useState<string | null>(null);
  const visible = useMemo(() => expenses.filter((expense) => type === "ALL" || expense.type === type).sort((a, b) => { if (sort === "highest") return Number(BigInt(b.amount) - BigInt(a.amount)); if (sort === "lowest") return Number(BigInt(a.amount) - BigInt(b.amount)); return sort === "oldest" ? new Date(a.date).getTime() - new Date(b.date).getTime() : new Date(b.date).getTime() - new Date(a.date).getTime(); }), [expenses, sort, type]);
  async function remove(expenseId: string) { if (!window.confirm("Удалить этот расход?")) return; setDeleting(expenseId); const response = await fetch(`/api/expenses/${expenseId}`, { method: "DELETE" }); if (!response.ok) alert("Не удалось удалить расход."); router.refresh(); setDeleting(null); }
  return <section className="mt-8"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-lg font-semibold">Расходы</h2><p className="mt-1 text-sm text-muted-foreground">{expenses.length} записей</p></div><ExpenseDialog projectId={projectId} /></div><div className="mt-5 flex flex-wrap gap-2"><select aria-label="Тип расхода" value={type} onChange={(event) => setType(event.target.value as typeof type)} className="h-9 rounded-lg border bg-card px-2 text-sm"><option value="ALL">Все расходы</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="Сортировка" value={sort} onChange={(event) => setSort(event.target.value)} className="h-9 rounded-lg border bg-card px-2 text-sm"><option value="newest">Сначала новые</option><option value="oldest">Сначала старые</option><option value="highest">Сначала дорогие</option><option value="lowest">Сначала дешёвые</option></select></div><div className="mt-4 overflow-hidden rounded-xl bg-card ring-1 ring-foreground/10">{visible.length === 0 ? <p className="p-7 text-center text-sm text-muted-foreground">Расходов с такими фильтрами нет.</p> : visible.map((expense) => <article key={expense.id} className="flex items-center gap-3 border-b p-4 last:border-0"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-x-2 gap-y-1"><h3 className="font-medium">{expense.title}</h3><span className="rounded-full bg-muted px-2 py-0.5 text-xs text-muted-foreground">{labels[expense.type]}</span></div><p className="mt-1 text-sm text-muted-foreground">{expense.employeeName || expense.vendorName || expense.description || new Intl.DateTimeFormat("ru-RU", { day: "numeric", month: "long", year: "numeric" }).format(new Date(expense.date))}</p></div><div className="text-right"><p className="font-semibold">{formatMoney(expense.amount)}</p><div className="mt-1 flex justify-end"><Button aria-label="Редактировать" variant="ghost" size="icon-sm" onClick={() => setEditing(expense)}><Pencil /></Button><Button aria-label="Удалить" variant="ghost" size="icon-sm" disabled={deleting === expense.id} onClick={() => remove(expense.id)}><Trash2 className="text-destructive" /></Button></div></div></article>)}</div>{editing && <ExpenseDialog projectId={projectId} expense={editing} open onOpenChange={(open) => !open && setEditing(null)} />}</section>;
}
