"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import type { ExpenseView } from "./expense-list";

const types = [{ value: "EMPLOYEE", label: "Сотрудник" }, { value: "MATERIAL", label: "Материалы" }, { value: "FUEL", label: "Топливо" }, { value: "TRANSPORT", label: "Транспорт" }, { value: "EQUIPMENT", label: "Оборудование" }, { value: "SERVICE", label: "Услуги" }, { value: "OTHER", label: "Другое" }];

export function ExpenseDialog({ projectId, expense, open, onOpenChange }: { projectId: string; expense?: ExpenseView; open?: boolean; onOpenChange?: (open: boolean) => void }) {
  const router = useRouter(); const [internalOpen, setInternalOpen] = useState(false); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false); const isOpen = open ?? internalOpen;
  function changeOpen(value: boolean) { setInternalOpen(value); onOpenChange?.(value); if (!value) setError(null); }
  async function submit(data: FormData) { setError(null); setPending(true); const url = expense ? `/api/expenses/${expense.id}` : `/api/projects/${projectId}/expenses`; const response = await fetch(url, { method: expense ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(data)) }); const payload = await response.json() as { error?: { message: string } }; if (!response.ok) { setError(payload.error?.message || "Не удалось сохранить расход."); setPending(false); return; } changeOpen(false); router.refresh(); setPending(false); }
  const date = expense?.date.slice(0, 10) || new Date().toISOString().slice(0, 10);
  return <Dialog open={isOpen} onOpenChange={changeOpen}>{!expense && <DialogTrigger render={<Button size="lg" />}><Plus />Добавить расход</DialogTrigger>}<DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-lg"><DialogHeader><DialogTitle>{expense ? "Изменить расход" : "Добавить расход"}</DialogTitle><DialogDescription>Обязательны только тип, название, сумма и дата.</DialogDescription></DialogHeader><form action={submit} className="grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-medium">Тип<select name="type" defaultValue={expense?.type || "EMPLOYEE"} className="h-8 rounded-lg border bg-transparent px-2 text-sm">{types.map((type) => <option key={type.value} value={type.value}>{type.label}</option>)}</select></label><label className="grid gap-1.5 text-sm font-medium">Дата<Input required name="date" type="date" defaultValue={date} /></label></div><label className="grid gap-1.5 text-sm font-medium">Название<Input required name="title" defaultValue={expense?.title} placeholder="Оплата штукатуру" /></label><label className="grid gap-1.5 text-sm font-medium">Сумма, ֏<Input required name="amount" inputMode="numeric" defaultValue={expense?.amount} placeholder="120000" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-medium">Кому заплачено<Input name="employeeName" defaultValue={expense?.employeeName || ""} placeholder="Армен" /></label><label className="grid gap-1.5 text-sm font-medium">Поставщик<Input name="vendorName" defaultValue={expense?.vendorName || ""} /></label></div><label className="grid gap-1.5 text-sm font-medium">Комментарий<textarea name="description" defaultValue={expense?.description || ""} rows={2} className="rounded-lg border bg-transparent px-2.5 py-2 text-sm outline-none focus-visible:ring-3 focus-visible:ring-ring/50" /></label><label className="grid gap-1.5 text-sm font-medium">Примечание <span className="font-normal text-muted-foreground">(необязательно)</span><Input name="notes" defaultValue={expense?.notes || ""} /></label>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Button type="submit" size="lg" disabled={pending}>{pending ? "Сохраняем…" : expense ? "Сохранить" : "Добавить расход"}</Button></form></DialogContent></Dialog>;
}
