import Link from "next/link";
import { ListTodo, Plus } from "lucide-react";

import { ProjectCard } from "@/components/projects/project-card";
import { ProjectEmptyState } from "@/components/projects/project-empty-state";
import { getAuthenticatedUser } from "@/server/auth";
import { getUserProjects } from "@/server/modules/projects/projects.service";
import { getActiveTaskCount } from "@/server/modules/tasks/tasks.service";
import { getTranslations } from "@/i18n/server";

export default async function DashboardPage() {
  const { locale, t } = await getTranslations();
  const user = await getAuthenticatedUser();
  const [projects, activeTaskCount] = await Promise.all([getUserProjects(user.id), getActiveTaskCount(user.id)]);
  const totalBudget = projects.reduce((sum, project) => sum + project.estimatedAmount, 0n);
  const totalSpent = projects.reduce((sum, project) => sum + project.spentAmount, 0n);
  const canEditProjects = user.role !== "MEMBER";
  const initials = (user.name || user.email || "U").slice(0, 2).toUpperCase();
  return <div className="mx-auto max-w-6xl px-5 pb-28 pt-6 sm:px-8 sm:pt-8">{user.approvalNote && <aside className="mb-6 rounded-2xl border border-primary/20 bg-primary/5 p-4 text-sm"><p className="font-medium">{t("dashboard.adminNote")}</p><p className="mt-1 whitespace-pre-wrap text-muted-foreground">{user.approvalNote}</p></aside>}<header className="mb-6 flex items-center justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-[0.16em] text-slate-400">SHINEX CRM</p><h1 className="mt-1 text-[28px] font-semibold tracking-[-0.045em] text-slate-950">{t("dashboard.projects")}</h1></div><div className="flex items-center gap-3"><Link href="/dashboard/tasks" className="inline-flex h-10 items-center gap-2 rounded-xl bg-blue-50 px-3 text-sm font-semibold text-blue-700 transition hover:bg-blue-100"><ListTodo className="size-4" />{t("dashboard.tasks")}{activeTaskCount > 0 && <span className="grid min-w-5 place-items-center rounded-full bg-blue-600 px-1.5 py-0.5 text-[10px] text-white">{activeTaskCount}</span>}</Link><div className="grid size-10 place-items-center rounded-full bg-gradient-to-br from-blue-600 to-indigo-700 text-xs font-bold text-white">{initials}</div></div></header>{projects.length > 0 && <section className="mb-7 overflow-hidden rounded-[22px] bg-slate-950 p-5 text-white shadow-[0_14px_35px_rgba(15,23,42,0.14)]"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-300">{t("dashboard.overview")}</p><p className="mt-1 text-3xl font-semibold tracking-[-0.055em]">{t("dashboard.projectsCount", { count: projects.length })}</p></div><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs font-medium text-slate-200">{t("dashboard.total")}</span></div><div className="mt-6 grid grid-cols-2 gap-4 border-t border-white/10 pt-4"><div><p className="text-xs text-slate-400">{t("dashboard.totalBudget")}</p><p className="mt-1 text-base font-semibold">{new Intl.NumberFormat(locale === "hy" ? "hy-AM" : "ru-RU", { notation: "compact", maximumFractionDigits: 1 }).format(totalBudget)} AMD</p></div><div><p className="text-xs text-slate-400">{t("dashboard.spent")}</p><p className="mt-1 text-base font-semibold">{new Intl.NumberFormat(locale === "hy" ? "hy-AM" : "ru-RU", { notation: "compact", maximumFractionDigits: 1 }).format(totalSpent)} AMD</p></div></div></section>}<div className="mb-4 flex items-center justify-between"><h2 className="text-base font-semibold tracking-[-0.02em] text-slate-900">{t("dashboard.yourProjects")}</h2>{canEditProjects && projects.length > 0 && <Link href="/dashboard/projects/new" className="inline-flex items-center gap-1 text-sm font-semibold text-blue-600"><Plus className="size-4" />{t("dashboard.new")}</Link>}</div>{projects.length === 0 ? <ProjectEmptyState canCreate={canEditProjects} /> : <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{projects.map((project) => <ProjectCard key={project.id} project={project} />)}</section>}</div>;
}
