import Link from "next/link";
import { Bell, Plus, Search } from "lucide-react";

import { ProjectCard } from "@/components/projects/project-card";
import { ProjectEmptyState } from "@/components/projects/project-empty-state";
import { getAuthenticatedUser } from "@/server/auth";
import { getUserProjects } from "@/server/modules/projects/projects.service";

export default async function DashboardPage() {
  const user = await getAuthenticatedUser();
  const projects = await getUserProjects(user.id);
  const totalBudget = projects.reduce((sum, project) => sum + project.estimatedAmount, 0n);
  const totalSpent = projects.reduce((sum, project) => sum + project.spentAmount, 0n);
  const initials = (user.name || user.email || "U").slice(0, 2).toUpperCase();
  return <div className="mx-auto max-w-6xl px-5 pb-28 pt-6 sm:px-8 sm:pt-8">{user.approvalNote && <aside className="mb-6 rounded-2xl border border-primary/20 bg-primary/5 p-4 text-sm"><p className="font-medium">Информация от администратора</p><p className="mt-1 whitespace-pre-wrap text-muted-foreground">{user.approvalNote}</p></aside>}<header className="mb-6 flex items-center justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-[0.16em] text-slate-400">SHINEX CRM</p><h1 className="mt-1 text-[28px] font-semibold tracking-[-0.045em] text-slate-950">Проекты</h1></div><div className="flex items-center gap-2"><button aria-label="Поиск" className="grid size-10 place-items-center rounded-full bg-white text-slate-700 shadow-sm ring-1 ring-slate-200"><Search className="size-[18px]" /></button><button aria-label="Уведомления" className="hidden size-10 place-items-center rounded-full bg-white text-slate-700 shadow-sm ring-1 ring-slate-200 sm:grid"><Bell className="size-[18px]" /></button><div className="grid size-10 place-items-center rounded-full bg-gradient-to-br from-blue-600 to-indigo-700 text-xs font-bold text-white">{initials}</div></div></header>{projects.length > 0 && <section className="mb-7 overflow-hidden rounded-[22px] bg-slate-950 p-5 text-white shadow-[0_14px_35px_rgba(15,23,42,0.14)]"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-300">Общий обзор</p><p className="mt-1 text-3xl font-semibold tracking-[-0.055em]">{projects.length}<span className="ml-1 text-base font-medium text-slate-400">активных</span></p></div><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs font-medium text-slate-200">Этот месяц</span></div><div className="mt-6 grid grid-cols-2 gap-4 border-t border-white/10 pt-4"><div><p className="text-xs text-slate-400">Общий бюджет</p><p className="mt-1 text-base font-semibold">{new Intl.NumberFormat("ru-RU", { notation: "compact", maximumFractionDigits: 1 }).format(Number(totalBudget))} AMD</p></div><div><p className="text-xs text-slate-400">Потрачено</p><p className="mt-1 text-base font-semibold">{new Intl.NumberFormat("ru-RU", { notation: "compact", maximumFractionDigits: 1 }).format(Number(totalSpent))} AMD</p></div></div></section>}<div className="mb-4 flex items-center justify-between"><h2 className="text-base font-semibold tracking-[-0.02em] text-slate-900">Ваши проекты</h2>{projects.length > 0 && <Link href="/dashboard/projects/new" className="inline-flex items-center gap-1 text-sm font-semibold text-blue-600"><Plus className="size-4" />Новый</Link>}</div>{projects.length === 0 ? <ProjectEmptyState /> : <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{projects.map((project) => <ProjectCard key={project.id} project={project} />)}</section>}</div>;
}
